module.exports = {
  // BASE_URL: 'http://192.168.0.159:3000/api/v8/',//local
  BASE_URL: 'http://174.138.60.52/api/v8/',//stagging
  // BASE_URL: 'http://165.227.79.51/api/v8/', //stagging mirror
  // BASE_URL: 'https://app.evvsystems.com/api/v8/',
  something_went_wrong: 'No internet connection available.',
  mobile: 'Please enter your mobile number',
  password: 'Please enter your password',
  invalid_mobile: 'Please enter valid mobile number',
  invalid_qr_code: 'Invalid QR code.',
  theme_color: '#004FBB',
  disabled_color: '#848f9e',
  success_color: '#00B325',
  error_color: '#cc3232',
  success_disabled: '#caf7d4',
  appointment_ended: 'You have failed to complete this appointment.',
  login_api_error_404: 'Something went wrong! Unable to login.',
  check_appointment_api_error_404: 'Something went wrong! Unable to fetch next appointment.',
  logout_api_error_404: 'Something went wrong! Unable to logout.',
  get_todo_list: 'Something went wrong! Unable to fetch care plans.',
  get_appointment_list: 'Something went wrong! Unable to fetch appointments.',
  check_in_api_error: 'Something went wrong! Unable to check in.',
  check_out_api_error: 'Something went wrong! Unable to check out.',
  ivr_check_in_alert: 'No internet connection. Please call: 844-302-3645 from Client\'s phone',
  ivr_check_out_alert: 'No internet connection. Please call: 844-302-3645 from Client\'s phone.',
  ivr_warning_in: "Please ensure that you check-in through IVR.",
  ivr_warning_out: "Please ensure that you check-Out through IVR.",
  Unable_to_find_app: "Unable to find appointment please call: 844-302-3645 to check appointment.",
  too_early_check_out: "Too early to checkout.",
  forgot_api_error_404: "Something went wrong! Unable to send new password.",
  reset_api_error_404: "Something went wrong! Unable to reset password.",
  otp_api_error_404: "Something went wrong! Unable to verify OTP.",
  client_select: "Please select client",
  get_client_list: "Something went wrong! Unable to fetch clients.",
  update_beacon_api: "Something went wrong! Unable to update Beacon.",
  verify_beacon_api: "Something went wrong! Unable to Verify Beacon.",
  client_invalid_select: "Please enter valid client name.",
  user_deactivate: 'You are forcefully logged out from the system as your current status is deactivated/deleted.',
  unable_to_update_notification: "Something went wrong! Unable to update.",
  unable_to_get_notification: "Something went wrong! Unable to fetch notifications.",
  unable_to_extend_appointment: "Something went wrong! Unable to extend appointment.",
  alert_sos: "Something went wrong! Unable to alert SOS.",
  get_hours: "Something went wrong! Unable to fetch hours",
  get_blog: "Something went wrong! Unable to fetch blog's.",
  no_blog: "You have no feeds yet or please check your internet connection and try again.",
  care_plan_submit_error: "Something went wrong! Unable to submit care plan.",
  submitted_careplan: "You have already submitted your checklist.",
  too_early_check_out_st: 'Are you sure you want to leave early?',
  live_in_submitted_careplan: 'Checklist Completed for today. Thank you and have a good night.',
  phone_switch: 'You are forcefully logged out from the system as you are logged into other device.',
  while_in_use: 'To increase battery efficiency please change your Location Services from Always to While in Use.',
  always: 'In order for your time to be properly recorded, please change Location Services from While in Use to Always.',
  get_incomplete_list: 'Something went wrong! Unable to fetch incomplete visits.',
  ongoing_visit: "You don't have any ongoing visit.",
  location_rssi_unavailable_message: 'There seem to be some issue, please try again after few minutes!',
  t_and_c_title: "Terms and Conditions",
  t_and_c_message: "We have updated our Terms and Conditions. Please agree to the Terms and Conditions.",
  t_and_c_button: "Continue",
  t_and_c_error: "Something went wrong! Unable to fetch terms and condition.",
  t_and_c_submit_error: "Something went wrong! Unable to accept terms and condition.",
  notAbleToCheckIn: 'You are not authorized to visit the client.',
  notAbleToSubmitChecklist: 'You are not authorized to use the Checklist',
  carePlanTitle: "Confirmation",
  carePlanMessage: "Are you sure you want to submit?"
};