module.exports = {
    // BASE_URL: 'http://192.168.0.159:3000/api/v8/',//local
    BASE_URL: 'http://174.138.60.52/api/v8/',//stagging
    // BASE_URL: 'http://165.227.79.51/api/v8/', //stagging mirror
    // BASE_URL: 'https://app.evvsystems.com/api/v8/',
    mobileNumber: '携帯電話番号',
    password: 'パスワード',
    singIn:	'サインイン',
    forgotPassword:	'パスワードをお忘れですか？',
    resetMobileInstruction: 'パスワードリセットの指示を送るために登録した携帯電話番号が必要です。',
    send: '送信',
    mobileVerify: '携帯電話番号の承認をしておりますのでしばらくお待ちください。',
    otpDetect: 'SMSが自動的に検出できない場合は、以下のワンタイムパスワード（OTP)を入力してください',
    enterOtp: 'ワンタイムパスワード（OTP)を入力',
    submit: '提出',
    resend: '再送信',
    resetYourPassword : 'パスワードをリセット',
    enterNewPassword:'アカウントの新しいパスワードを入力してください。',
    newPassword: '新しいパスワード',
    confirmPassword: 'パスワードをもう一度入力してください',
    pleasWait: '少々お待ちください',
    help: 'ヘルプ',
    checkIn: 'チェックイン',
    scanQRCodeCheckIn: 'QRコードをスキャンしてチェックインします',
    tasks: 'タスク',
    checkOut: 'チェックアウト',
    scanQRCodeCheckOut: 'QRコードをスキャンしてチェックアウトする',
    skip: 'スキップ',
    done: '完了',
    extraActivity: '追加活動',
    anyInjuriesClient: '患者様またはご自身に負傷などはありませんでしたか？',
    anyReimbursementMilage: '払い戻しマイルを持っていますか？',
    timeLeave: '何時に出発しましたか？',
    hourlyVisit: '毎時訪問',
    unitSetup: 'ユニットのセットアップ',
    enterClientName: 'クライアント名を入力',
    next: '次',
    unitLinkedToclient: '<Client Name>にリンクされているユニットこれが正しい場合は、Confirmをクリックしてください',
    confirm: '確認',
    confirmUnit : '単位を確認する',
    verifyUnitSetup: 'ユニットの検証を確認する',
    unitSetupVerified: '<Client Name>のユニット設定が確認されました。',
    ok: 'OK',
    verification: '検証',
    news: 'ニュース',
    changePassword: 'パスワードを変更する',
    changeYourPassword: 'パスワードを変更してください',
    enterNewPasswordAccount: 'あなたのアカウントの新しいパスワードを入力してください。',
    currentPassword : '現在のパスワード',
    newPassword: '新しいパスワード',
    changePassword: "パスワードを変更する",
    settings: '設定',
    camera: 'カメラ',
    location: 'ロケーション',
    termsOfUse : '利用規約',
    logout: 'ログアウト',
    scan : 'スキャン',
    visitsRequireAttention: '11回の訪問であなたの注意が必要です',
    appointmentInfo: '予約情報',
    noNextScheduling: '次回のスケジューリングはありません。',
    nextAppointmentInfo: '次回の予定は2018-09-10です。時間：午後7時30分〜午後8時',
    checkInToViewTask: '今日の仕事を見るにはチェックインしてください。',
    yes: 'はい',
    no: 'いいえ',
    refused : '拒否',
    schedules : 'スケジュール',
    signature: '署名',
    clientSignature: 'クライアントの署名',
    reset: 'リセット',
    save: 'セーブ',
    scanQrCode: 'QRコードをスキャンする',
    welcomToOmin: 'オムニトラッキングシステムへようこそ',
    mangeYourWork: 'あなたの仕事を迅速かつ効率的に管理してください。',
    noAppointments: '予定はありません。',
    pending: '保留中',
    working: 'ワーキング',
    completed : '完了しました',
    notAttended : '出席していない',
    incomplete : '不完全な',
    logoutCheckOut: 'ログアウトチェックアウト',
    notifications: '通知',
    noNotificationYet: 'まだ通知はありません！',
    refereshNotitification: 'まだ通知はありません！',
    callMe: '電話してね',
    runningLate: '遅れています',
    onMyWay: '行く途中です',
    from: 'から',
    message : 'メッセージ',
    hoursAgo : '時間前',
    clear: 'クリア',
    goodMorning : 'おはようございます',
    goodAfternoon : "こんにちは",
    goodEvening : 'こんばんは',
    visitStarts30Min: '"新しい顧客とのあなたの訪問は30分後に始まります。',
    timeToReach: '届くまでにどれくらい時間がかかりますか？',
    cancel: 'キャンセル',
    scheduleTimeChange: '現在のスケジュールの終了時刻が午後4時に変更されました',
    taskUpdated: 'あなたの現在の仕事は更新されました。',
    seemsForgotToCheckout: 'チェックアウトを忘れたようです。<クライアント名>のスケジュールを延長しますか？',
    markedIncomplete: 'クライアント<Client Name>のスケジュールが不完全としてマークされています。',
    approvedVisit: '予約された訪問がクライアント<クライアント名>に対して承認されました！',
    declinedVisit: 'クライアント<Client Name>の予約訪問が拒否されました。',
    visitUpdatedCheckOut: "予定された訪問：クライアント '<クライアント名>'のチェックアウト時間が '4/11/2018 04:30 AM'から '4/11/2018 04:34 AM'に更新されました。",
    visitUpdatedCheckIn: "予定された訪問：クライアント '<クライアント名>'のチェックイン時間が '4/11/2018 04:30 AM'から '4/11/2018 04:34 AM'に更新されました",
    extendedHourUpdate: "予定された訪問：2010年7月23日の訪問の延長時間が、クライアント<クライアント名>の'00：00 'から'01：10'に更新されました。",
    completeTaskNow: 'お支払いを受けるには、今すぐ仕事を完了してください。',
    something_went_wrong: 'インターネットに接続できません。',
    mobile: 'あなたの携帯電話番号を入力してください',
    password: 'パスワードを入力してください',
    invalid_mobile: '有効な携帯電話番号を入力してください',
    mobileNotFoundForUser: '有効な携帯電話番号を入力してください',
    mobileNotFound: '携帯電話番号が見つかりません',
    invalidCred: '無効な資格情報',
    successLogin: 'ありがとうございました。',
    successOtp: 'ありがとうございました！ OTPはSMS経由で送信されます',
    enterOtp: 'OTPを入力してください',
    otpVerificationFailed: 'OTPの確認に失敗しました！',
    otpVerifiedSuccess: 'OTP verifeidが成功しました！',
    enterNewPasswordMsg: '確認パスワードを入力してください',
    enterConfirmPasswordMsg: '確認パスワードを入力してください', 
    passwordNotMatch: '新しいパスワードと確認パスワードが一致しません',
    passwordResetSuccess: 'ありがとうございました！あなたのパスワードは正常にリセットされました',
    enterCurrentPassword : '現在のパスワードを入力してください',
    invalidCurrentPassword: '現在のパスワードが無効です。正しいパスワードを入力してください。',
    selectClient: 'クライアントを選択してください',
    nameAlreadyTaken: '名前は既に取られている',
    validClientName: '有効なクライアント名を入力してください',
    unitAssociatedWithOtherClient: 'このユニットは他のクライアントに関連付けられています',
    unableToFetchLocation: 'あなたの場所を取得できません。もう一度お試しください。',
    unitUpdated: '<クライアント名>のユニットが更新されました',
    unitIdIsInvalid: 'ユニットIDが無効です',
    unitIsAssociatedWithSelectedClinet: 'このユニットは、すでに選択したクライアントに関連付けられています。',
    submitAllTask: 'すべてのタスクを提出してください',
    failedToCompleteAppointment: '提出してもよろしいですか？ "',
    checkInSuccess: 'ありがとうございました。',
    checkOutSuccess: '正常にチェックアウトしていただきありがとうございます',
    tooEarly: '早すぎる！あなたのアポイントメントは今日<appointment start_time>から始まります。',
    taskSubmitted: 'ありがとう、タスクが正常に送信されました',
    unableToFingLocationTryAgain: ' あなたの場所を見つけることができません。もう一度お試しください',
    logout : 'ログアウト',
    areYouSureWantToLogout: 'ログアウトしてもよろしいですか？',
    remoteCheckOutSuccess: 'この予約を完了できませんでした。',

    invalid_qr_code: 'Invalid QR code.',
    theme_color: '#004FBB',
    disabled_color: '#848f9e',
    success_color: '#00B325',
    error_color: '#cc3232',
    success_disabled: '#caf7d4',
    appointment_ended: 'You have failed to complete this appointment.',
    login_api_error_404: '何かが間違っていた！ログインできません。',
    check_appointment_api_error_404: '何かが間違っていた！次のアポイントを取得できません',
    logout_api_error_404: '何かが間違っていた！ログアウトできません。',
    get_todo_list: '何かが間違っていた！タスクを取得できません.',
    get_appointment_list: '何かが間違っていた！予定を取得できません',
    check_in_api_error: '何かが間違っていた！チェックインできません.',
    check_out_api_error: '何かが間違っていた！チェックアウトできません.',
    ivr_check_in_alert: 'No internet connection. Please call: 844-302-3645 from Client\'s phone',
    ivr_check_out_alert: 'No internet connection. Please call: 844-302-3645 from Client\'s phone.',
    ivr_warning_in: "Please ensure that you check-in through IVR.",
    ivr_warning_out: "Please ensure that you check-Out through IVR.",
    Unable_to_find_app: "Unable to find appointment please call: 844-302-3645 to check appointment.",
    too_early_check_out: "Too early to checkout.",
    forgot_api_error_404: "何かが間違っていた！新しいパスワードを送信できません",
    reset_api_error_404: "何かが間違っていた！パスワードをリセットできません。",
    otp_api_error_404: "何かが間違っていた！ OTPを確認できません。.",
    get_client_list: "何かが間違っていた！クライアントを取得できません.",
    update_beacon_api: "何かが間違っていた！ビーコンを更新できません。",
    verify_beacon_api: "何かが間違っていた！ビーコンを確認できません。",
    client_invalid_select: "Please enter valid client name.",
    user_deactivate: '現在のステータスが無効/削除されると、強制的にシステムからログアウトされます。',
    unable_to_update_notification: "何かが間違っていた！更新できません.",
    unable_to_get_notification: "何かが間違っていた！通知を取得できません。",
    unable_to_extend_appointment: "何かが間違っていた！予定を延長できません.",
    alert_sos: "Something went wrong! Unable to alert SOS.",
    get_hours: "Something went wrong! Unable to fetch hours",
    get_blog: "Something went wrong! Unable to fetch blog's.",
    no_blog: "他のデバイスにログインしている間は、強制的にシステムからログアウトします。",
    care_plan_submit_error: "Something went wrong! Unable to submit care plan.",
    submitted_careplan: "You have already submitted your checklist.",
    too_early_check_out_st: 'Are you sure you want to leave early?',
    live_in_submitted_careplan: 'Checklist Completed for today. Thank you and have a good night.',
    phone_switch: 'You are forcefully logged out from the system as you are logged into other device.',
    while_in_use: 'バッテリーの効率を上げるには、ロケーションサービスを常に使用中から使用中に変更してください。',
    always: '時間が正しく記録されるためには、ロケーションサービスを使用中から常時に変更してください。',
    get_incomplete_list: 'Something went wrong! Unable to fetch incomplete visits.',
    ongoing_visit: "進行中の訪問はありません。",
    location_rssi_unavailable_message: '何か問題があるようですが、数分後にもう一度お試しください！',
    t_and_c_title: "Terms and Conditions",
    t_and_c_message: "私たちは利用規約を更新しました。利用規約に同意してください。",
    t_and_c_button: "持続する",
    t_and_c_error: "何かが間違っていた！利用規約を取得できません。",
    t_and_c_submit_error: "何かが間違っていた！利用規約に同意できません。",
    notAbleToCheckIn: 'あなたはクライアントにアクセスする権限がありません。',
    notAbleToSubmitChecklist: 'あなたはタスクを使用する権限がありません',
    carePlanTitle: "Confirmation",
    carePlanMessage: "Are you sure you want to submit?"
  };